/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        panel: 'var(--panel)',
        'panel-muted': 'var(--panel-muted)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',
        'text-soft': 'var(--text-soft)',
        brand: 'var(--brand)',
        'brand-hover': 'var(--brand-hover)',
        'brand-strong': 'var(--brand-strong)',
        'brand-soft': 'var(--brand-soft)',
        'brand-soft-2': 'var(--brand-soft-2)',
        accent: 'var(--accent)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        danger: 'var(--danger)',
        'danger-soft': 'var(--danger-soft)',
        'chart-grid': 'var(--chart-grid)',
        'chart-axis': 'var(--chart-axis)',
        'ig-pink': 'var(--ig-pink)',
        'ig-purple': 'var(--ig-purple)',
        'ig-orange': 'var(--ig-orange)',
        'ig-blue': 'var(--ig-blue)',
        'ig-violet': 'var(--ig-violet)',
        'ig-yellow': 'var(--ig-yellow)',
        'ig-red': 'var(--ig-red)',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'var(--font-display)'],
        body: ['"Plus Jakarta Sans"', 'var(--font-body)'],
      },
      borderRadius: {
        'card': 'var(--radius-lg)',
        'card-sm': 'var(--radius-md)',
        'inner': 'var(--radius-sm)',
        'pill': 'var(--radius-pill)',
      },
      boxShadow: {
        'panel-sm': 'var(--shadow-sm)',
        'panel-md': 'var(--shadow-md)',
        'panel-lg': 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
}
